### ISSUE TITLE
Show Card example does not work

### ISSUE THREAD

**Issue by adyah-cisco** [webex/webex-node-bot-framework#27]
Not just the example, any valid card does not work, get the error below:

```bash
# node testCard.js 
LoggerProxy->info#NO LOGGER DEFINED
(node:328516) UnhandledPromiseRejectionWarning: BadRequest: Missing Adaptive Card Version
POST https://hydra-a.wbx2.com/v1/messages
WEBEX_TRACKING_ID: webex-js-sdk_<ID>

    at BadRequest.ExtendableBuiltin (/home/adyanth/webex-bot/node_modules/@webex/common/dist/exception.js:50:44)
    at BadRequest.Exception (/home/adyanth/webex-bot/node_modules/@webex/common/dist/exception.js:97:142)
    at BadRequest.HttpError (/home/adyanth/webex-bot/node_modules/@webex/http-core/dist/http-error.js:69:125)
    at BadRequest.WebexHttpError (/home/adyanth/webex-bot/node_modules/@webex/webex-core/dist/lib/webex-http-error.js:48:135)
    at new BadRequest (/home/adyanth/webex-bot/node_modules/@webex/http-core/dist/http-error-subtypes.js:63:129)
    at HttpStatusInterceptor.onResponse (/home/adyanth/webex-bot/node_modules/@webex/http-core/dist/interceptors/http-status.js:108:39)
    at /home/adyanth/webex-bot/node_modules/@webex/http-core/dist/request/index.js:69:41
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:328516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
```

Framework version: "webex-node-bot-framework": "^2.1.1"

**Comment by jpjpjp** [comment]
Hi @adyah-cisco .   What is testCard.js?

Is it possible that the problem is with this application since there are many framework based apps that do work with cards that include Action.ShowCard elements?

Happy to help you shake this out if you can provide more details.   For a faster response post your details to  [Framework Support Space on Webex Teams](https://eurl.io/#BJ7gmlSeU).
